config/routes.rb
Rails.application.routes.draw do
  root 'families#show', id: '1'
  devise_for :users
  resources :families do
    resources :family_members
  end
  resources :adventures do
    resources :contributions
  end
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adventure.rb
class Adventure < ApplicationRecord
  belongs_to :family
  belongs_to :family_member, optional: true
  has_many   :contributions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :contributor
  belongs_to :adventure
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  belongs_to :user
end

app/models/family.rb
class Family < ApplicationRecord
  has_many :family_members
  has_many :adventures
  belongs_to :users
end

app/models/family_member.rb
class FamilyMember < ApplicationRecord
  belongs_to :family
  has_many :adventures
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :family
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  before_action :set_adventure, only: [:show, :edit, :update, :destroy]

  # GET /adventures
  # GET /adventures.json
  def index
    @adventures = Adventure.all
  end

  # GET /adventures/1
  # GET /adventures/1.json
  def show
  end

  # GET /adventures/new
  def new
    @adventure = Adventure.new
  end

  # GET /adventures/1/edit
  def edit
  end

  # POST /adventures
  # POST /adventures.json
  def create
    @adventure = Adventure.new(adventure_params)

    respond_to do |format|
      if @adventure.save
        format.html { redirect_to @adventure, notice: 'Adventure was successfully created.' }
        format.json { render :show, status: :created, location: @adventure }
      else
        format.html { render :new }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adventures/1
  # PATCH/PUT /adventures/1.json
  def update
    respond_to do |format|
      if @adventure.update(adventure_params)
        format.html { redirect_to @adventure, notice: 'Adventure was successfully updated.' }
        format.json { render :show, status: :ok, location: @adventure }
      else
        format.html { render :edit }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adventures/1
  # DELETE /adventures/1.json
  def destroy
    @adventure.destroy
    respond_to do |format|
      format.html { redirect_to adventures_url, notice: 'Adventure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adventure
      @adventure = Adventure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adventure_params
      params.require(:adventure).permit(:title, :description, :cost, :family_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:show, :edit, :update, :destroy]
  rescue_from Stripe::CardError, with: :catch_exception

  def index
    @contributions = Contribution.all
  end

  def new
  end

  def create
    @contribution = Contribution.new(contribution_params)
    if @contribution.save
      StripeChargesServices.new(contribution_params, current_user).call
      puts "************************"
      puts params
      redirect_to adventure_contributions_path(contribution_params[:adventure][:family_member_id])
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contribution
      @contribution = Contribution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contribution_params
      params.permit(:amount, :contributor, :adventure_id, :stripeEmail, :stripeToken, :utf8, :authenticity_token, :stripeTokenType)
    end

    def catch_exception(exception)
      flash[:error] = exception.message
    end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: [:show, :edit, :update, :destroy]

  # GET /families
  # GET /families.json
  def index
    @families = Family.all
  end

  # GET /families/1
  # GET /families/1.json
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families
  # POST /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to @family, notice: 'Family was successfully created.' }
        format.json { render :show, status: :created, location: @family }
      else
        format.html { render :new }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /families/1
  # PATCH/PUT /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to @family, notice: 'Family was successfully updated.' }
        format.json { render :show, status: :ok, location: @family }
      else
        format.html { render :edit }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1
  # DELETE /families/1.json
  def destroy
    @family.destroy
    respond_to do |format|
      format.html { redirect_to families_url, notice: 'Family was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_params
      params.require(:family).permit(:title, :description, :cost, :family_id)
    end
end

app/controllers/family_members_controller.rb
class FamilyMembersController < ApplicationController
  before_action :set_family, only: [:show]

  def show
    @contribution = Contribution.new
  end

  # GET /families/new
  # def new
  #   @family = Family.new
  # end

  # GET /families/1/edit
  # def edit
  # end

  # POST /families
  # POST /families.json
  # def create
  #   @family = Family.new(family_params)
  #
  #   respond_to do |format|
  #     if @family.save
  #       format.html { redirect_to @family, notice: 'Family was successfully created.' }
  #       format.json { render :show, status: :created, location: @family }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @family.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /families/1
  # # PATCH/PUT /families/1.json
  # def update
  #   respond_to do |format|
  #     if @family.update(family_params)
  #       format.html { redirect_to @family, notice: 'Family was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @family }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @family.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /families/1
  # # DELETE /families/1.json
  # def destroy
  #   @family.destroy
  #   respond_to do |format|
  #     format.html { redirect_to families_url, notice: 'Family was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family_member = FamilyMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_params
      params.require(:family_member).permit(:full_name, :age, :family_id)
    end
end

app/helpers/adventures_helper.rb
module AdventuresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/adventures/_form.html.erb
<%= form_with(model: adventure, local: true) do |form| %>
  <% if adventure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(adventure.errors.count, "error") %> prohibited this adventure from being saved:</h2>

      <ul>
      <% adventure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost %>
  </div>

  <div class="field">
    <%= form.label :family_id %>
    <%= form.text_field :family_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/adventures/edit.html.erb
<h1>Editing Adventure</h1>

<%= render 'form', adventure: @adventure %>

<%= link_to 'Show', @adventure %> |
<%= link_to 'Back', adventures_path %>

app/views/adventures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Adventures</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Cost</th>
      <th>Family</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adventures.each do |adventure| %>
      <tr>
        <td><%= adventure.title %></td>
        <td><%= adventure.description %></td>
        <td><%= adventure.cost %></td>
        <td><%= adventure.family %></td>
        <td><%= link_to 'Show', adventure %></td>
        <td><%= link_to 'Edit', edit_adventure_path(adventure) %></td>
        <td><%= link_to 'Destroy', adventure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adventure', new_adventure_path %>

app/views/adventures/new.html.erb
<h1>New Adventure</h1>

<%= render 'form', adventure: @adventure %>

<%= link_to 'Back', adventures_path %>

app/views/adventures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @adventure.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @adventure.description %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @adventure.cost %>
</p>

<p>
  <strong>Family:</strong>
  <%= @adventure.family.name %>
</p>

<p>
  <strong>Family Member:</strong>
  <%= @adventure&.family_member&.full_name %>
</p>

<%= link_to 'Edit', edit_adventure_path(@adventure) %> |
<%= link_to 'Back', adventures_path %>

app/views/contributions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contributions</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contributions.each do |contribution| %>
      <tr>
        <td><%= contribution.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contributions/new.html.erb
<h1>Contribute</h1>

app/views/families/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Families</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @families.each do |family| %>
      <tr>
        <td><%= family.name %></td>
        <td><%= link_to 'Show', family %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/families/show.html.erb
<p id="notice"><%= notice %></p>
<h1 class="uk-text-center"><%= @family.name %> Family</h1>
<p class="uk-container">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure ullam quisquam fugit sequi
  molestiae fugiat sit, odit nobis tempora officia. Voluptatibus facilis, laudantium commodi cum earum distinctio
  quisquam mollitia sequi. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure ullam quisquam fugit sequi
  molestiae fugiat sit, odit nobis tempora officia. Voluptatibus facilis, laudantium commodi cum earum distinctio
  quisquam mollitia sequi. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure ullam quisquam fugit
  sequi molestiae fugiat sit, odit nobis tempora officia. Voluptatibus facilis, laudantium commodi cum earum distinctio
   quisquam mollitia sequi.</p>

<div class="uk-section uk-section-muted uk-preserve-color">
    <div class="uk-container">
        <div class="uk-grid-match uk-child-width-expand@m" uk-grid>
          <% @family.family_members.each do |family_member| %>
            <div>
              <%= link_to(family_family_member_path(@family, family_member)) do %>
              <div class="uk-card uk-card-secondary uk-card-body uk-card-hover">
                <h3 class="uk-text-center"><%= family_member.full_name %></h3>
              </div>
              <% end %>
            </div>
          <% end %>
        </div>

    </div>
</div>

<div class="uk-section uk-section-secondary uk-preserve-color">
  <div class="uk-container">
    <div class="uk-panel uk-light uk-margin-medium">
      <h3>Adventures</h3>
    </div>
    <div class="uk-grid-match uk-child-width-expand@m" uk-grid>
      <% if @family.adventures.where(family_member_id: nil).empty? %>
        <p>This family does not yet have any adventures planned!</p>
      <% else %>
        <% @family.adventures.where(family_member_id: nil).each do |adventure| %>
        <div>
          <div class="uk-card uk-card-default uk-card-body">
            <h3 class="uk-card-title uk-inline"><%= adventure.title %><span class="uk-badge ml10 mb3">$<%= adventure.cost %></span></h3>
            <p><%= adventure.description %></p>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/family_members/show.html.erb
<p id="notice"><%= notice %></p>
<ul class="uk-breadcrumb">
    <li><%= link_to "#{@family_member.family.name} Family", family_path(@family_member.family_id) %></li>
    <li><%= @family_member.full_name %></li>
</ul>
<h2 class="uk-text-center"><%= @family_member.full_name %></h2>

<% if @family_member.adventures.any? %>
  <div class="uk-section uk-section-secondary uk-preserve-color">
    <div class="uk-container">
      <div class="uk-panel uk-light uk-margin-medium">
        <h3>Adventures</h3>
      </div>
      <div class="uk-grid-match uk-child-width-expand@m" uk-grid>
        <% @family_member.adventures.each do |adventure| %>
        <div>
          <div class="uk-card uk-card-default uk-card-body">
            <h3 class="uk-card-title"><%= adventure.title%><span class="uk-badge ml10 mb3">$<%= adventure.cost %></span></h3>
            <p><%= adventure.description %></p>
            <button class="uk-button uk-button-default uk-margin-small-right" type="button" uk-toggle="target: #modal-example">Contribute</button>
            <!-- This is the modal -->
            <div id="modal-example" uk-modal>
              <div class="uk-modal-dialog uk-modal-body">
                <h2 class="uk-modal-title">How much do you want to contribute to this adventure?</h2>
                  <%= form_with(url: adventure_contributions_path(adventure_id: adventure.id, contributor: current_user), local: true) do |form| %>
                    <% if flash[:error].present? %>
                      <div id="error_explanation">
                        <p><%= flash[:error] %></p>
                      </div>
                    <% end %>
                    <div class="field">
                      <%= form.label :amount %>
                      <%= form.text_field :amount, class: "uk-input" %>
                    </div>

                    <div class="actions uk-text-right mt10">
                      <button class="uk-button uk-button-default uk-modal-close mr10" type="button">Cancel</button>
                      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" style="uk-button uk-button-default"
                        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                        data-description="Contributing to Adventure"
                        data-amount=""
                        data-locale="auto">
                      </script>
                    </div>
                  <% end %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <div class="uk-text-center">This family member does not have any individual adventures yet!</div>
<% end %>

<%= link_to family_path(@family_member.family_id), class: "uk-button uk-button-secondary mt10 ml10" do %>
  <span uk-icon="arrow-left"></span>Back
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdventuresOverThings</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.22/css/uikit.min.css" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- UIkit JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.22/js/uikit.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.22/js/uikit-icons.min.js"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="root">
    <%= yield %>
    </div>
  </body>
</html>